
networks: 
  jmb-dev:

services:
  btcreader-backend:
    build: ./backend
    image: ${BACKEND_IMAGE_NAME}:${VER_NUM}
    container_name: btcreader-backend
    working_dir: /backend
    command: npm run server
    restart: always
    depends_on:
      - btcreader-postgres
    environment:
      - _DB_PASSWORD=b7cre@d3r
      - POSTGRES_PASSWORD=samplepassword
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT_NUMBER}:${BACKEND_PORT_NUMBER}
    networks:
      - jmb-dev


  btcreader-postgres:
    build: ./database
    image: ${DB_IMAGE_NAME}:${VER_NUM}
    container_name: ${DB_CONTAINER_NAME}
    # for restoring data dumps of table
    working_dir: /sqlexport
    restart: always
    environment:
      - _DB_PASSWORD=b7cre@d3r
      - POSTGRES_PASSWORD=samplepassword
    env_file:
      - .env
    ports:
      - ${DB_PORT_NUMBER}:${DB_PORT_NUMBER}
    networks:
      - jmb-dev 
