
networks: 
  jmb-dev:

services:
  btcreader-frontend:
    build: ./frontend
    image: ${FRONTEND_IMAGE_NAME}:${VER_NUM}
    container_name: btcreader-frontend
    working_dir: /frontend/serve
    command: npm run server
    #tty: true
    restart: always
    env_file:
      - .env
    ports:
      - ${FRONTEND_PORT_NUMBER}:${FRONTEND_PORT_NUMBER}
    networks:
      - jmb-dev


  btcreader-backend:
    build: ./backend
    image: ${BACKEND_IMAGE_NAME}:${VER_NUM}
    container_name: btcreader-backend
    working_dir: /backend
    command: npm run server
    restart: always
    depends_on:
      - btcreader-postgres
    environment:
      - _DB_PASSWORD=b7cre@d3r
      - POSTGRES_PASSWORD=samplepassword
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT_NUMBER}:${BACKEND_PORT_NUMBER}
    networks:
      - jmb-dev


  btcreader-postgres:
    build: ./database
    image: ${DB_IMAGE_NAME}:${VER_NUM}
    container_name: ${DB_CONTAINER_NAME}
    # for restoring data dumps of table
    working_dir: /sqlexport
    restart: always
    environment:
      - _DB_PASSWORD=b7cre@d3r
      - POSTGRES_PASSWORD=samplepassword
    env_file:
      - .env
    ports:
      - ${DB_PORT_NUMBER}:${DB_PORT_NUMBER}
    networks:
      - jmb-dev 


  btcreader-swaggerui:
    build: 
      context: ./swagger-ui
      dockerfile: Dockerfile
      args:
        backend_api: ${REACT_APP_FETCH_ENDPOINT}
    image: ${SWAGGER_UI_IMAGE_NAME}:${VER_NUM}
    container_name: btcreader-swaggerui
    working_dir: /
    restart: always
    environment:
      - BASE_URL=/api-docs
      - SWAGGER_JSON=/swaggerdoc/btcreader-swagger.json
    env_file:
      - .env
    ports:
      - ${SWAGGER_UI_PORT}:8080
    networks:
      - jmb-dev